version: '3.6'

services:

  postgres:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=opensea
      - DATABASE_HOST=postgres
    ports:
      - "5432:5432"
    networks:
      - learning

  opensea_app:
    # Configuration for building the docker image for the service
    build:
      context: . # Use an image built from the specified dockerfile in the current directory.
      dockerfile: Dockerfile
    ports:
      - "8081:8081" # Forward the exposed port 8081 on the container to port 8080 on the host machine
    tty: true
    networks:
      - learning  
    restart: on-failure
    depends_on: 
      - postgres # This service depends on postgres. Start that first.

networks:
  learning:
    driver: bridge      
      